"use client";

import {useRef,useState,type HTMLAttributes} from 'react';
import {useCinema} from './hooks/useCinema';
import {CinemaAudio} from './audio/CinemaAudio';
import {ArrowDown,ArrowUpRight,Volume2,VolumeX,ArrowRight} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
const chapters=['Introduction','The journey','Cloud migration','AI & lineage','Performance','What I offer'];
const skills=['Snowflake','Teradata','SQL','Python','PySpark','Informatica','Hadoop','DB2','Snowflake Cortex','AI Agents'];
function CinematicChapter({children,...props}:HTMLAttributes<HTMLElement>){return <div className="reel"><section {...props}>{children}<canvas className="data-motion" aria-hidden="true"/><div className="cinema-vignette" aria-hidden="true"/><div className="chapter-progress" aria-hidden="true"><span/></div></section></div>;}
export default function Home(){
const [active,setActive]=useState(0),[sound,setSound]=useState(false),[evidence,setEvidence]=useState<number|null>(null);
const audio=useRef<CinemaAudio|null>(null),soundRef=useRef(false),last=useRef(0);
const go=(n:number)=>window.dispatchEvent(new CustomEvent('visume:navigate',{detail:n}));
function ping(n=active,reveal=false){if(soundRef.current)audio.current?.play([0,4,1,2,3,4][n],reveal);}
function toggleSound(){const next=!sound;try{if(next)audio.current??=new CinemaAudio();audio.current?.enable(next);soundRef.current=next;setSound(next);if(next)audio.current?.play([0,4,1,2,3,4][active]);}catch{soundRef.current=false;setSound(false);}}
useCinema(null,n=>{setActive(n);if(last.current!==n){ping(n);last.current=n;}},n=>ping(n,true));

const facts=[{title:'Cloud migration',quote:'“Spearheaded large-scale data migrations from Teradata and Hadoop to Snowflake, handing over 300 tables and 1 TB of data with minimal downtime and data inconsistency post-cutover.”',note:'Source: Employment History · EY / Morgan Stanley'},{title:'AI-powered lineage',quote:'“Built a unified application using ChatGPT and Claude AI agents to capture data lineage, expanding coverage from 1 to 10 Product teams.”',note:'Source: Employment History · EY / Morgan Stanley'},{title:'Batch performance',quote:'“Optimized the legacy job framework to remove redundant steps and cut batch processing time from 10 hours to 7 hours.”',note:'30% reduction calculated from the times in your resume.'}];
return <main>
<header className="topbar"><a className="brand" href="#chapter-0"><span className="brand-mark">v</span>visume<span className="brand-dot">.</span></a><div className="top-middle"><span className="tiny-line"/> A RESUME, REIMAGINED</div></header>
<aside className="chapter-nav" aria-label="Resume chapters">{chapters.map((name,i)=><button key={name} onClick={()=>go(i)} aria-label={name} aria-current={active===i?'step':undefined} className={active===i?'selected':''}><span className="nav-name">{name}</span><span className="nav-line"/></button>)}</aside>
<>
<CinematicChapter className="chapter hero seen" id="chapter-0" data-index="0" data-visual-index="0"><img className="scene intro-scene" src="images/intro.webp" alt="A luminous glass structure surrounded by flowing data trails"/><div className="shade"/><div className="chapter-content"><p className="eyebrow"><span/> VINAY JAKKULA <span className="eyebrow-divider">/</span> DATA ENGINEER</p><h1>Behind the data.<br/><em>A bigger story.</em></h1><p className="intro-copy">I turn complex data into dependable systems.<br/>And ambitious ideas into measurable impact.</p><div className="hero-actions"><button className="primary" onClick={()=>go(1)}>Explore my story <ArrowDown size={17}/></button><span className="location">HYDERABAD, INDIA</span></div><div className="hero-stats"><div><strong>7<span>+</span></strong><p>Years in data engineering</p></div><div><strong>10<span>×</span></strong><p>Lineage team coverage</p></div><div><strong>30<span>%</span></strong><p>Less batch processing time</p></div></div></div><div className="art-caption"><span>01 / THE DATA ARCHITECT</span><p>Complexity, made clear.</p></div><div className="scroll-hint"><span/> SCROLL TO REVEAL</div></CinematicChapter>
<CinematicChapter className="chapter journey" id="chapter-1" data-index="1" data-visual-index="4"><div className="journey-top"><div><p className="eyebrow">01 / THE PERSON BEHIND THE PIPELINES</p><h2>Built with experience.<br/><em>Driven by curiosity.</em></h2></div><div className="experience"><div><span>EY · MORGAN STANLEY</span><h3>Data Engineer</h3><p>Led a six-member team across integration, migrations, and delivery.</p></div><div><span>DEC 2018 — MAY 2022</span><h3>Tata Consultancy Services</h3><p>Data Engineer · Genuine Parts Company<br/>ETL development, production reliability, and Python automation.</p></div></div></div><div className="skills-strip">{skills.map(s=><span key={s}>{s}</span>)}</div><div className="recognition-grid"><div><p>RECOGNITION</p><h3>Client Extraordinaire</h3><span>EY · FY 23–24 & FY 25–26</span></div><div><p>CONSISTENT IMPACT</p><h3>3 consecutive awards</h3><span>TCS On-The-Spot · FY 2021–22</span></div><div><p>INNOVATION</p><h3>Joblens</h3><span>GRIT Awards nominee · 2026</span></div></div><div className="journey-footer"><p>B.Tech (ME) · RGUKT, Basar · 2014–2018</p><a href="https://www.linkedin.com/in/vinayjakkula" target="_blank" rel="noreferrer">Let’s connect <ArrowUpRight size={18}/></a></div></CinematicChapter>
<CinematicChapter className="chapter" id="chapter-2" data-index="2" data-visual-index="1"><img className="scene" src="images/migration.webp" alt="Glass data blocks moving into a luminous modern structure"/><div className="shade"/><div className="chapter-content"><p className="eyebrow">02 / CLOUD MODERNIZATION</p><h2>Big moves.<br/><em>Built on trust.</em></h2><p className="intro-copy">From Teradata and Hadoop to Snowflake.<br/>Enterprise migrations designed around continuity, consistency, and scale.</p><div className="metric-row"><div><strong>300</strong><span>tables migrated</span></div><div><strong>1 TB</strong><span>of data moved</span></div></div><div className="tags"><span>Snowflake</span><span>Teradata</span><span>Hadoop</span></div><button className="text-button" onClick={()=>setEvidence(0)}>Read the resume detail <ArrowUpRight size={16}/></button></div><div className="art-caption"><span>EY · MORGAN STANLEY</span><p>New foundations. Same confidence.</p></div></CinematicChapter>
<CinematicChapter className="chapter" id="chapter-3" data-index="3" data-visual-index="2"><img className="scene" src="images/lineage.webp" alt="An intricate network of luminous fibers representing data lineage"/><div className="shade"/><div className="chapter-content"><p className="eyebrow">03 / INTELLIGENCE, CONNECTED</p><h2>Every data point.<br/><em>A clearer path.</em></h2><p className="intro-copy">Built a unified AI-driven lineage application and used Snowflake LLMs and a Cortex agent to make cross-system data easier to trace and query.</p><div className="lineage-metric"><span>1</span><ArrowRight/><strong>10</strong></div><p className="metric-label">Product teams covered</p><div className="tags"><span>AI Agents</span><span>Snowflake Cortex</span><span>Data Lineage</span></div><button className="text-button" onClick={()=>setEvidence(1)}>Read the resume detail <ArrowUpRight size={16}/></button></div></CinematicChapter>
<CinematicChapter className="chapter performance" id="chapter-4" data-index="4" data-visual-index="3"><img className="scene" src="images/migration.webp" alt="Luminous data structures in motion"/><div className="shade"/><div className="chapter-content"><p className="eyebrow">04 / ENGINEERED FOR IMPACT</p><h2>Less waiting.<br/><em>More possibility.</em></h2><p className="intro-copy">Removed redundant steps from a legacy job framework. Reclaimed three hours from every batch run.</p><button className="text-button" onClick={()=>setEvidence(2)}>Read the resume detail <ArrowUpRight size={16}/></button></div><div className="performance-chart"><div className="chart-header"><span>BATCH PROCESSING TIME</span><span>HOURS / RUN</span></div><div className="bar-label"><span>Before optimization</span><strong>10 h</strong></div><div className="bar old"><span/></div><div className="bar-label"><span>After optimization</span><strong>7 h</strong></div><div className="bar new"><span/></div><div className="saving"><strong>30<span>%</span></strong><div>less processing time<br/><span>3 hours returned to the day.</span></div></div></div></CinematicChapter>
<CinematicChapter className="chapter offer" id="chapter-5" data-index="5" data-visual-index="0" aria-label="What I bring to your team"><img className="scene" src="images/intro.webp" alt=""/><div className="shade"/><div className="offer-content"><p className="eyebrow">05 / WHAT I BRING TO YOUR TEAM</p><h2>Your next data challenge.<br/><em>My next chapter.</em></h2><p className="offer-intro">An engineer who connects hands-on delivery with team ownership.<br/>Here’s where I can make a difference.</p><div className="offer-grid"><article><span className="offer-number">01</span><h3>Modernize with confidence.</h3><p>Move legacy data platforms to Snowflake with careful validation and continuity in mind.</p><span className="offer-proof">Delivered: 300 tables · 1 TB migrated</span></article><article><span className="offer-number">02</span><h3>Give time back to your team.</h3><p>Simplify ETL workflows, remove redundant processing, and focus on measurable improvements.</p><span className="offer-proof">Delivered: batch time cut from 10 h to 7 h</span></article><article><span className="offer-number">03</span><h3>Make complex data clearer.</h3><p>Apply AI agents and Snowflake Cortex to help teams trace lineage and understand their data.</p><span className="offer-proof">Delivered: lineage coverage from 1 to 10 teams</span></article><article><span className="offer-number">04</span><h3>Take ownership. Bring people along.</h3><p>Combine hands-on engineering with coordination across integration, migration, and delivery.</p><span className="offer-proof">Experience: led a six-member team</span></article></div><div className="offer-footer"><div><p>Building a data team?</p><span>Let’s talk about the challenge you need solved.</span></div><a className="primary" href="https://www.linkedin.com/in/vinayjakkula" target="_blank" rel="noreferrer">Let’s discuss your role <ArrowUpRight size={18}/></a></div></div></CinematicChapter></>
<footer className="bottom-bar"><span><b>{String(active+1).padStart(2,'0')}</b> / {String(chapters.length).padStart(2,'0')} <i/> {chapters[active]}</span><button onClick={toggleSound} aria-pressed={sound}>{sound?<Volume2 size={16}/>:<VolumeX size={16}/>} Sound {sound?'on':'off'}</button></footer>
<Dialog open={evidence!==null} onOpenChange={v=>{if(!v)setEvidence(null);}}><DialogContent className="evidence-dialog"><DialogTitle>{evidence!==null?facts[evidence].title:''}</DialogTitle><DialogDescription>Grounded in your September 2026 resume.</DialogDescription>{evidence!==null&&<><blockquote>{facts[evidence].quote}</blockquote><p className="source-note">{facts[evidence].note}</p><p className="source-note">Artwork is a conceptual illustration of the achievement.</p></>}</DialogContent></Dialog>
</main>;
}
